// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Clever/clever-go/v4/client/courses"
	"github.com/Clever/clever-go/v4/client/districts"
	"github.com/Clever/clever-go/v4/client/events"
	"github.com/Clever/clever-go/v4/client/resources"
	"github.com/Clever/clever-go/v4/client/schools"
	"github.com/Clever/clever-go/v4/client/sections"
	"github.com/Clever/clever-go/v4/client/terms"
	"github.com/Clever/clever-go/v4/client/users"
)

// Default clever HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.clever.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new clever HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Clever {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new clever HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Clever {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new clever client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Clever {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Clever)
	cli.Transport = transport
	cli.Courses = courses.New(transport, formats)
	cli.Districts = districts.New(transport, formats)
	cli.Events = events.New(transport, formats)
	cli.Resources = resources.New(transport, formats)
	cli.Schools = schools.New(transport, formats)
	cli.Sections = sections.New(transport, formats)
	cli.Terms = terms.New(transport, formats)
	cli.Users = users.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Clever is a client for clever
type Clever struct {
	Courses courses.ClientService

	Districts districts.ClientService

	Events events.ClientService

	Resources resources.ClientService

	Schools schools.ClientService

	Sections sections.ClientService

	Terms terms.ClientService

	Users users.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Clever) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Courses.SetTransport(transport)
	c.Districts.SetTransport(transport)
	c.Events.SetTransport(transport)
	c.Resources.SetTransport(transport)
	c.Schools.SetTransport(transport)
	c.Sections.SetTransport(transport)
	c.Terms.SetTransport(transport)
	c.Users.SetTransport(transport)
}
