// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSchoolsForUserHandlerFunc turns a function with the right signature into a get schools for user handler
type GetSchoolsForUserHandlerFunc func(GetSchoolsForUserParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSchoolsForUserHandlerFunc) Handle(params GetSchoolsForUserParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetSchoolsForUserHandler interface for that can handle valid get schools for user params
type GetSchoolsForUserHandler interface {
	Handle(GetSchoolsForUserParams, interface{}) middleware.Responder
}

// NewGetSchoolsForUser creates a new http.Handler for the get schools for user operation
func NewGetSchoolsForUser(ctx *middleware.Context, handler GetSchoolsForUserHandler) *GetSchoolsForUser {
	return &GetSchoolsForUser{Context: ctx, Handler: handler}
}

/* GetSchoolsForUser swagger:route GET /users/{id}/schools Users getSchoolsForUser

Returns the schools for a user

*/
type GetSchoolsForUser struct {
	Context *middleware.Context
	Handler GetSchoolsForUserHandler
}

func (o *GetSchoolsForUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSchoolsForUserParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
