// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetStudentsForUserHandlerFunc turns a function with the right signature into a get students for user handler
type GetStudentsForUserHandlerFunc func(GetStudentsForUserParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetStudentsForUserHandlerFunc) Handle(params GetStudentsForUserParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetStudentsForUserHandler interface for that can handle valid get students for user params
type GetStudentsForUserHandler interface {
	Handle(GetStudentsForUserParams, interface{}) middleware.Responder
}

// NewGetStudentsForUser creates a new http.Handler for the get students for user operation
func NewGetStudentsForUser(ctx *middleware.Context, handler GetStudentsForUserHandler) *GetStudentsForUser {
	return &GetStudentsForUser{Context: ctx, Handler: handler}
}

/* GetStudentsForUser swagger:route GET /users/{id}/mystudents Users getStudentsForUser

Returns the student users for a teacher or contact user

*/
type GetStudentsForUser struct {
	Context *middleware.Context
	Handler GetStudentsForUserHandler
}

func (o *GetStudentsForUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetStudentsForUserParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
