// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSectionsForResourceHandlerFunc turns a function with the right signature into a get sections for resource handler
type GetSectionsForResourceHandlerFunc func(GetSectionsForResourceParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSectionsForResourceHandlerFunc) Handle(params GetSectionsForResourceParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetSectionsForResourceHandler interface for that can handle valid get sections for resource params
type GetSectionsForResourceHandler interface {
	Handle(GetSectionsForResourceParams, interface{}) middleware.Responder
}

// NewGetSectionsForResource creates a new http.Handler for the get sections for resource operation
func NewGetSectionsForResource(ctx *middleware.Context, handler GetSectionsForResourceHandler) *GetSectionsForResource {
	return &GetSectionsForResource{Context: ctx, Handler: handler}
}

/*
	GetSectionsForResource swagger:route GET /resources/{id}/sections Resources getSectionsForResource

Returns the sections for a resource
*/
type GetSectionsForResource struct {
	Context *middleware.Context
	Handler GetSectionsForResourceHandler
}

func (o *GetSectionsForResource) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSectionsForResourceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
