/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type DistrictStatusResponses struct {

	Data []DistrictStatusResponse `json:"data,omitempty"`
}
