/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type DistrictAdminResponse struct {

	Data DistrictAdmin `json:"data,omitempty"`
}
