/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Principal struct {

	Email string `json:"email,omitempty"`

	Name string `json:"name,omitempty"`
}
