/* 
 * Clever API
 *
 * The Clever API
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Term struct {

	EndDate string `json:"end_date,omitempty"`

	Name string `json:"name,omitempty"`

	StartDate string `json:"start_date,omitempty"`
}
