// Code generated by go-swagger; DO NOT EDIT.

package schools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetUsersForSchoolHandlerFunc turns a function with the right signature into a get users for school handler
type GetUsersForSchoolHandlerFunc func(GetUsersForSchoolParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUsersForSchoolHandlerFunc) Handle(params GetUsersForSchoolParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetUsersForSchoolHandler interface for that can handle valid get users for school params
type GetUsersForSchoolHandler interface {
	Handle(GetUsersForSchoolParams, interface{}) middleware.Responder
}

// NewGetUsersForSchool creates a new http.Handler for the get users for school operation
func NewGetUsersForSchool(ctx *middleware.Context, handler GetUsersForSchoolHandler) *GetUsersForSchool {
	return &GetUsersForSchool{Context: ctx, Handler: handler}
}

/*
	GetUsersForSchool swagger:route GET /schools/{id}/users Schools getUsersForSchool

Returns the staff, student, and/or teacher users for a school
*/
type GetUsersForSchool struct {
	Context *middleware.Context
	Handler GetUsersForSchoolHandler
}

func (o *GetUsersForSchool) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetUsersForSchoolParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
