// Code generated by go-swagger; DO NOT EDIT.

package schools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSchoolHandlerFunc turns a function with the right signature into a get school handler
type GetSchoolHandlerFunc func(GetSchoolParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSchoolHandlerFunc) Handle(params GetSchoolParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetSchoolHandler interface for that can handle valid get school params
type GetSchoolHandler interface {
	Handle(GetSchoolParams, interface{}) middleware.Responder
}

// NewGetSchool creates a new http.Handler for the get school operation
func NewGetSchool(ctx *middleware.Context, handler GetSchoolHandler) *GetSchool {
	return &GetSchool{Context: ctx, Handler: handler}
}

/*
	GetSchool swagger:route GET /schools/{id} Schools getSchool

Returns a specific school
*/
type GetSchool struct {
	Context *middleware.Context
	Handler GetSchoolHandler
}

func (o *GetSchool) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSchoolParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
