// Code generated by go-swagger; DO NOT EDIT.

package schools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Clever/clever-go/models"
)

// GetSchoolsOKCode is the HTTP code returned for type GetSchoolsOK
const GetSchoolsOKCode int = 200

/*
GetSchoolsOK OK Response

swagger:response getSchoolsOK
*/
type GetSchoolsOK struct {

	/*
	  In: Body
	*/
	Payload *models.SchoolsResponse `json:"body,omitempty"`
}

// NewGetSchoolsOK creates GetSchoolsOK with default headers values
func NewGetSchoolsOK() *GetSchoolsOK {

	return &GetSchoolsOK{}
}

// WithPayload adds the payload to the get schools o k response
func (o *GetSchoolsOK) WithPayload(payload *models.SchoolsResponse) *GetSchoolsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get schools o k response
func (o *GetSchoolsOK) SetPayload(payload *models.SchoolsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSchoolsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
