// Code generated by go-swagger; DO NOT EDIT.

package schools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSchoolsHandlerFunc turns a function with the right signature into a get schools handler
type GetSchoolsHandlerFunc func(GetSchoolsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSchoolsHandlerFunc) Handle(params GetSchoolsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetSchoolsHandler interface for that can handle valid get schools params
type GetSchoolsHandler interface {
	Handle(GetSchoolsParams, interface{}) middleware.Responder
}

// NewGetSchools creates a new http.Handler for the get schools operation
func NewGetSchools(ctx *middleware.Context, handler GetSchoolsHandler) *GetSchools {
	return &GetSchools{Context: ctx, Handler: handler}
}

/* GetSchools swagger:route GET /schools Schools getSchools

Returns a list of schools

*/
type GetSchools struct {
	Context *middleware.Context
	Handler GetSchoolsHandler
}

func (o *GetSchools) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSchoolsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
