// Code generated by go-swagger; DO NOT EDIT.

package districts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Clever/clever-go/v4/models"
)

// GetDistrictsOKCode is the HTTP code returned for type GetDistrictsOK
const GetDistrictsOKCode int = 200

/*GetDistrictsOK OK Response

swagger:response getDistrictsOK
*/
type GetDistrictsOK struct {

	/*
	  In: Body
	*/
	Payload *models.DistrictsResponse `json:"body,omitempty"`
}

// NewGetDistrictsOK creates GetDistrictsOK with default headers values
func NewGetDistrictsOK() *GetDistrictsOK {

	return &GetDistrictsOK{}
}

// WithPayload adds the payload to the get districts o k response
func (o *GetDistrictsOK) WithPayload(payload *models.DistrictsResponse) *GetDistrictsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get districts o k response
func (o *GetDistrictsOK) SetPayload(payload *models.DistrictsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDistrictsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
