// Code generated by go-swagger; DO NOT EDIT.

package districts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Clever/clever-go/models"
)

// GetDistrictsReader is a Reader for the GetDistricts structure.
type GetDistrictsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDistrictsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDistrictsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /districts] getDistricts", response, response.Code())
	}
}

// NewGetDistrictsOK creates a GetDistrictsOK with default headers values
func NewGetDistrictsOK() *GetDistrictsOK {
	return &GetDistrictsOK{}
}

/*
GetDistrictsOK describes a response with status code 200, with default header values.

OK Response
*/
type GetDistrictsOK struct {
	Payload *models.DistrictsResponse
}

// IsSuccess returns true when this get districts o k response has a 2xx status code
func (o *GetDistrictsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get districts o k response has a 3xx status code
func (o *GetDistrictsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get districts o k response has a 4xx status code
func (o *GetDistrictsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get districts o k response has a 5xx status code
func (o *GetDistrictsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get districts o k response a status code equal to that given
func (o *GetDistrictsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get districts o k response
func (o *GetDistrictsOK) Code() int {
	return 200
}

func (o *GetDistrictsOK) Error() string {
	return fmt.Sprintf("[GET /districts][%d] getDistrictsOK  %+v", 200, o.Payload)
}

func (o *GetDistrictsOK) String() string {
	return fmt.Sprintf("[GET /districts][%d] getDistrictsOK  %+v", 200, o.Payload)
}

func (o *GetDistrictsOK) GetPayload() *models.DistrictsResponse {
	return o.Payload
}

func (o *GetDistrictsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DistrictsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
