// Code generated by go-swagger; DO NOT EDIT.

package sections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCourseForSectionHandlerFunc turns a function with the right signature into a get course for section handler
type GetCourseForSectionHandlerFunc func(GetCourseForSectionParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCourseForSectionHandlerFunc) Handle(params GetCourseForSectionParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetCourseForSectionHandler interface for that can handle valid get course for section params
type GetCourseForSectionHandler interface {
	Handle(GetCourseForSectionParams, interface{}) middleware.Responder
}

// NewGetCourseForSection creates a new http.Handler for the get course for section operation
func NewGetCourseForSection(ctx *middleware.Context, handler GetCourseForSectionHandler) *GetCourseForSection {
	return &GetCourseForSection{Context: ctx, Handler: handler}
}

/*
	GetCourseForSection swagger:route GET /sections/{id}/course Sections getCourseForSection

Returns the course for a section
*/
type GetCourseForSection struct {
	Context *middleware.Context
	Handler GetCourseForSectionHandler
}

func (o *GetCourseForSection) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCourseForSectionParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
