// Code generated by go-swagger; DO NOT EDIT.

package sections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Clever/clever-go/models"
)

// GetSectionsOKCode is the HTTP code returned for type GetSectionsOK
const GetSectionsOKCode int = 200

/*GetSectionsOK OK Response

swagger:response getSectionsOK
*/
type GetSectionsOK struct {

	/*
	  In: Body
	*/
	Payload *models.SectionsResponse `json:"body,omitempty"`
}

// NewGetSectionsOK creates GetSectionsOK with default headers values
func NewGetSectionsOK() *GetSectionsOK {

	return &GetSectionsOK{}
}

// WithPayload adds the payload to the get sections o k response
func (o *GetSectionsOK) WithPayload(payload *models.SectionsResponse) *GetSectionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sections o k response
func (o *GetSectionsOK) SetPayload(payload *models.SectionsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSectionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
