// Code generated by go-swagger; DO NOT EDIT.

package sections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDistrictForSectionHandlerFunc turns a function with the right signature into a get district for section handler
type GetDistrictForSectionHandlerFunc func(GetDistrictForSectionParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDistrictForSectionHandlerFunc) Handle(params GetDistrictForSectionParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetDistrictForSectionHandler interface for that can handle valid get district for section params
type GetDistrictForSectionHandler interface {
	Handle(GetDistrictForSectionParams, interface{}) middleware.Responder
}

// NewGetDistrictForSection creates a new http.Handler for the get district for section operation
func NewGetDistrictForSection(ctx *middleware.Context, handler GetDistrictForSectionHandler) *GetDistrictForSection {
	return &GetDistrictForSection{Context: ctx, Handler: handler}
}

/* GetDistrictForSection swagger:route GET /sections/{id}/district Sections getDistrictForSection

Returns the district for a section

*/
type GetDistrictForSection struct {
	Context *middleware.Context
	Handler GetDistrictForSectionHandler
}

func (o *GetDistrictForSection) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDistrictForSectionParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
