// Code generated by go-swagger; DO NOT EDIT.

package sections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Clever/clever-go/v4/models"
)

// GetCourseForSectionReader is a Reader for the GetCourseForSection structure.
type GetCourseForSectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCourseForSectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCourseForSectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetCourseForSectionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCourseForSectionOK creates a GetCourseForSectionOK with default headers values
func NewGetCourseForSectionOK() *GetCourseForSectionOK {
	return &GetCourseForSectionOK{}
}

/* GetCourseForSectionOK describes a response with status code 200, with default header values.

OK Response
*/
type GetCourseForSectionOK struct {
	Payload *models.CourseResponse
}

func (o *GetCourseForSectionOK) Error() string {
	return fmt.Sprintf("[GET /sections/{id}/course][%d] getCourseForSectionOK  %+v", 200, o.Payload)
}
func (o *GetCourseForSectionOK) GetPayload() *models.CourseResponse {
	return o.Payload
}

func (o *GetCourseForSectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CourseResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCourseForSectionNotFound creates a GetCourseForSectionNotFound with default headers values
func NewGetCourseForSectionNotFound() *GetCourseForSectionNotFound {
	return &GetCourseForSectionNotFound{}
}

/* GetCourseForSectionNotFound describes a response with status code 404, with default header values.

Entity Not Found
*/
type GetCourseForSectionNotFound struct {
	Payload *models.NotFound
}

func (o *GetCourseForSectionNotFound) Error() string {
	return fmt.Sprintf("[GET /sections/{id}/course][%d] getCourseForSectionNotFound  %+v", 404, o.Payload)
}
func (o *GetCourseForSectionNotFound) GetPayload() *models.NotFound {
	return o.Payload
}

func (o *GetCourseForSectionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NotFound)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
