// Code generated by go-swagger; DO NOT EDIT.

package sections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSchoolForSectionParams creates a new GetSchoolForSectionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSchoolForSectionParams() *GetSchoolForSectionParams {
	return &GetSchoolForSectionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSchoolForSectionParamsWithTimeout creates a new GetSchoolForSectionParams object
// with the ability to set a timeout on a request.
func NewGetSchoolForSectionParamsWithTimeout(timeout time.Duration) *GetSchoolForSectionParams {
	return &GetSchoolForSectionParams{
		timeout: timeout,
	}
}

// NewGetSchoolForSectionParamsWithContext creates a new GetSchoolForSectionParams object
// with the ability to set a context for a request.
func NewGetSchoolForSectionParamsWithContext(ctx context.Context) *GetSchoolForSectionParams {
	return &GetSchoolForSectionParams{
		Context: ctx,
	}
}

// NewGetSchoolForSectionParamsWithHTTPClient creates a new GetSchoolForSectionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSchoolForSectionParamsWithHTTPClient(client *http.Client) *GetSchoolForSectionParams {
	return &GetSchoolForSectionParams{
		HTTPClient: client,
	}
}

/* GetSchoolForSectionParams contains all the parameters to send to the API endpoint
   for the get school for section operation.

   Typically these are written to a http.Request.
*/
type GetSchoolForSectionParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get school for section params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSchoolForSectionParams) WithDefaults() *GetSchoolForSectionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get school for section params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSchoolForSectionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get school for section params
func (o *GetSchoolForSectionParams) WithTimeout(timeout time.Duration) *GetSchoolForSectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get school for section params
func (o *GetSchoolForSectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get school for section params
func (o *GetSchoolForSectionParams) WithContext(ctx context.Context) *GetSchoolForSectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get school for section params
func (o *GetSchoolForSectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get school for section params
func (o *GetSchoolForSectionParams) WithHTTPClient(client *http.Client) *GetSchoolForSectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get school for section params
func (o *GetSchoolForSectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get school for section params
func (o *GetSchoolForSectionParams) WithID(id string) *GetSchoolForSectionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get school for section params
func (o *GetSchoolForSectionParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetSchoolForSectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
