// Code generated by go-swagger; DO NOT EDIT.

package sections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Clever/clever-go/models"
)

// GetResourcesForSectionReader is a Reader for the GetResourcesForSection structure.
type GetResourcesForSectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetResourcesForSectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetResourcesForSectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetResourcesForSectionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetResourcesForSectionOK creates a GetResourcesForSectionOK with default headers values
func NewGetResourcesForSectionOK() *GetResourcesForSectionOK {
	return &GetResourcesForSectionOK{}
}

/*
	GetResourcesForSectionOK describes a response with status code 200, with default header values.

OK Response
*/
type GetResourcesForSectionOK struct {
	Payload *models.ResourcesResponse
}

func (o *GetResourcesForSectionOK) Error() string {
	return fmt.Sprintf("[GET /sections/{id}/resources][%d] getResourcesForSectionOK  %+v", 200, o.Payload)
}
func (o *GetResourcesForSectionOK) GetPayload() *models.ResourcesResponse {
	return o.Payload
}

func (o *GetResourcesForSectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourcesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetResourcesForSectionNotFound creates a GetResourcesForSectionNotFound with default headers values
func NewGetResourcesForSectionNotFound() *GetResourcesForSectionNotFound {
	return &GetResourcesForSectionNotFound{}
}

/*
	GetResourcesForSectionNotFound describes a response with status code 404, with default header values.

Entity Not Found
*/
type GetResourcesForSectionNotFound struct {
	Payload *models.NotFound
}

func (o *GetResourcesForSectionNotFound) Error() string {
	return fmt.Sprintf("[GET /sections/{id}/resources][%d] getResourcesForSectionNotFound  %+v", 404, o.Payload)
}
func (o *GetResourcesForSectionNotFound) GetPayload() *models.NotFound {
	return o.Payload
}

func (o *GetResourcesForSectionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NotFound)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
