// Code generated by go-swagger; DO NOT EDIT.

package sections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCourseForSectionParams creates a new GetCourseForSectionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCourseForSectionParams() *GetCourseForSectionParams {
	return &GetCourseForSectionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCourseForSectionParamsWithTimeout creates a new GetCourseForSectionParams object
// with the ability to set a timeout on a request.
func NewGetCourseForSectionParamsWithTimeout(timeout time.Duration) *GetCourseForSectionParams {
	return &GetCourseForSectionParams{
		timeout: timeout,
	}
}

// NewGetCourseForSectionParamsWithContext creates a new GetCourseForSectionParams object
// with the ability to set a context for a request.
func NewGetCourseForSectionParamsWithContext(ctx context.Context) *GetCourseForSectionParams {
	return &GetCourseForSectionParams{
		Context: ctx,
	}
}

// NewGetCourseForSectionParamsWithHTTPClient creates a new GetCourseForSectionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCourseForSectionParamsWithHTTPClient(client *http.Client) *GetCourseForSectionParams {
	return &GetCourseForSectionParams{
		HTTPClient: client,
	}
}

/* GetCourseForSectionParams contains all the parameters to send to the API endpoint
   for the get course for section operation.

   Typically these are written to a http.Request.
*/
type GetCourseForSectionParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get course for section params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCourseForSectionParams) WithDefaults() *GetCourseForSectionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get course for section params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCourseForSectionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get course for section params
func (o *GetCourseForSectionParams) WithTimeout(timeout time.Duration) *GetCourseForSectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get course for section params
func (o *GetCourseForSectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get course for section params
func (o *GetCourseForSectionParams) WithContext(ctx context.Context) *GetCourseForSectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get course for section params
func (o *GetCourseForSectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get course for section params
func (o *GetCourseForSectionParams) WithHTTPClient(client *http.Client) *GetCourseForSectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get course for section params
func (o *GetCourseForSectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get course for section params
func (o *GetCourseForSectionParams) WithID(id string) *GetCourseForSectionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get course for section params
func (o *GetCourseForSectionParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetCourseForSectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
