// Code generated by go-swagger; DO NOT EDIT.

package sections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSectionParams creates a new GetSectionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSectionParams() *GetSectionParams {
	return &GetSectionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSectionParamsWithTimeout creates a new GetSectionParams object
// with the ability to set a timeout on a request.
func NewGetSectionParamsWithTimeout(timeout time.Duration) *GetSectionParams {
	return &GetSectionParams{
		timeout: timeout,
	}
}

// NewGetSectionParamsWithContext creates a new GetSectionParams object
// with the ability to set a context for a request.
func NewGetSectionParamsWithContext(ctx context.Context) *GetSectionParams {
	return &GetSectionParams{
		Context: ctx,
	}
}

// NewGetSectionParamsWithHTTPClient creates a new GetSectionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSectionParamsWithHTTPClient(client *http.Client) *GetSectionParams {
	return &GetSectionParams{
		HTTPClient: client,
	}
}

/* GetSectionParams contains all the parameters to send to the API endpoint
   for the get section operation.

   Typically these are written to a http.Request.
*/
type GetSectionParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get section params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSectionParams) WithDefaults() *GetSectionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get section params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSectionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get section params
func (o *GetSectionParams) WithTimeout(timeout time.Duration) *GetSectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get section params
func (o *GetSectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get section params
func (o *GetSectionParams) WithContext(ctx context.Context) *GetSectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get section params
func (o *GetSectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get section params
func (o *GetSectionParams) WithHTTPClient(client *http.Client) *GetSectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get section params
func (o *GetSectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get section params
func (o *GetSectionParams) WithID(id string) *GetSectionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get section params
func (o *GetSectionParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetSectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
