// Code generated by go-swagger; DO NOT EDIT.

package terms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSchoolsForTermHandlerFunc turns a function with the right signature into a get schools for term handler
type GetSchoolsForTermHandlerFunc func(GetSchoolsForTermParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSchoolsForTermHandlerFunc) Handle(params GetSchoolsForTermParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetSchoolsForTermHandler interface for that can handle valid get schools for term params
type GetSchoolsForTermHandler interface {
	Handle(GetSchoolsForTermParams, interface{}) middleware.Responder
}

// NewGetSchoolsForTerm creates a new http.Handler for the get schools for term operation
func NewGetSchoolsForTerm(ctx *middleware.Context, handler GetSchoolsForTermHandler) *GetSchoolsForTerm {
	return &GetSchoolsForTerm{Context: ctx, Handler: handler}
}

/*
	GetSchoolsForTerm swagger:route GET /terms/{id}/schools Terms getSchoolsForTerm

Returns the schools for a term
*/
type GetSchoolsForTerm struct {
	Context *middleware.Context
	Handler GetSchoolsForTermHandler
}

func (o *GetSchoolsForTerm) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSchoolsForTermParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
