// Code generated by go-swagger; DO NOT EDIT.

package terms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Clever/clever-go/models"
)

// GetTermsOKCode is the HTTP code returned for type GetTermsOK
const GetTermsOKCode int = 200

/*
GetTermsOK OK Response

swagger:response getTermsOK
*/
type GetTermsOK struct {

	/*
	  In: Body
	*/
	Payload *models.TermsResponse `json:"body,omitempty"`
}

// NewGetTermsOK creates GetTermsOK with default headers values
func NewGetTermsOK() *GetTermsOK {

	return &GetTermsOK{}
}

// WithPayload adds the payload to the get terms o k response
func (o *GetTermsOK) WithPayload(payload *models.TermsResponse) *GetTermsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get terms o k response
func (o *GetTermsOK) SetPayload(payload *models.TermsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTermsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
