// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Clever/clever-go/models"
)

// GetUsersForResourceReader is a Reader for the GetUsersForResource structure.
type GetUsersForResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUsersForResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUsersForResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetUsersForResourceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /resources/{id}/users] getUsersForResource", response, response.Code())
	}
}

// NewGetUsersForResourceOK creates a GetUsersForResourceOK with default headers values
func NewGetUsersForResourceOK() *GetUsersForResourceOK {
	return &GetUsersForResourceOK{}
}

/*
GetUsersForResourceOK describes a response with status code 200, with default header values.

OK Response
*/
type GetUsersForResourceOK struct {
	Payload *models.UsersResponse
}

// IsSuccess returns true when this get users for resource o k response has a 2xx status code
func (o *GetUsersForResourceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get users for resource o k response has a 3xx status code
func (o *GetUsersForResourceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get users for resource o k response has a 4xx status code
func (o *GetUsersForResourceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get users for resource o k response has a 5xx status code
func (o *GetUsersForResourceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get users for resource o k response a status code equal to that given
func (o *GetUsersForResourceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get users for resource o k response
func (o *GetUsersForResourceOK) Code() int {
	return 200
}

func (o *GetUsersForResourceOK) Error() string {
	return fmt.Sprintf("[GET /resources/{id}/users][%d] getUsersForResourceOK  %+v", 200, o.Payload)
}

func (o *GetUsersForResourceOK) String() string {
	return fmt.Sprintf("[GET /resources/{id}/users][%d] getUsersForResourceOK  %+v", 200, o.Payload)
}

func (o *GetUsersForResourceOK) GetPayload() *models.UsersResponse {
	return o.Payload
}

func (o *GetUsersForResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UsersResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsersForResourceNotFound creates a GetUsersForResourceNotFound with default headers values
func NewGetUsersForResourceNotFound() *GetUsersForResourceNotFound {
	return &GetUsersForResourceNotFound{}
}

/*
GetUsersForResourceNotFound describes a response with status code 404, with default header values.

Entity Not Found
*/
type GetUsersForResourceNotFound struct {
	Payload *models.NotFound
}

// IsSuccess returns true when this get users for resource not found response has a 2xx status code
func (o *GetUsersForResourceNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get users for resource not found response has a 3xx status code
func (o *GetUsersForResourceNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get users for resource not found response has a 4xx status code
func (o *GetUsersForResourceNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get users for resource not found response has a 5xx status code
func (o *GetUsersForResourceNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get users for resource not found response a status code equal to that given
func (o *GetUsersForResourceNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get users for resource not found response
func (o *GetUsersForResourceNotFound) Code() int {
	return 404
}

func (o *GetUsersForResourceNotFound) Error() string {
	return fmt.Sprintf("[GET /resources/{id}/users][%d] getUsersForResourceNotFound  %+v", 404, o.Payload)
}

func (o *GetUsersForResourceNotFound) String() string {
	return fmt.Sprintf("[GET /resources/{id}/users][%d] getUsersForResourceNotFound  %+v", 404, o.Payload)
}

func (o *GetUsersForResourceNotFound) GetPayload() *models.NotFound {
	return o.Payload
}

func (o *GetUsersForResourceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NotFound)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
