// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Clever/clever-go/models"
)

// GetStudentsForUserReader is a Reader for the GetStudentsForUser structure.
type GetStudentsForUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStudentsForUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStudentsForUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetStudentsForUserNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /users/{id}/mystudents] getStudentsForUser", response, response.Code())
	}
}

// NewGetStudentsForUserOK creates a GetStudentsForUserOK with default headers values
func NewGetStudentsForUserOK() *GetStudentsForUserOK {
	return &GetStudentsForUserOK{}
}

/*
GetStudentsForUserOK describes a response with status code 200, with default header values.

OK Response
*/
type GetStudentsForUserOK struct {
	Payload *models.UsersResponse
}

// IsSuccess returns true when this get students for user o k response has a 2xx status code
func (o *GetStudentsForUserOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get students for user o k response has a 3xx status code
func (o *GetStudentsForUserOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get students for user o k response has a 4xx status code
func (o *GetStudentsForUserOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get students for user o k response has a 5xx status code
func (o *GetStudentsForUserOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get students for user o k response a status code equal to that given
func (o *GetStudentsForUserOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get students for user o k response
func (o *GetStudentsForUserOK) Code() int {
	return 200
}

func (o *GetStudentsForUserOK) Error() string {
	return fmt.Sprintf("[GET /users/{id}/mystudents][%d] getStudentsForUserOK  %+v", 200, o.Payload)
}

func (o *GetStudentsForUserOK) String() string {
	return fmt.Sprintf("[GET /users/{id}/mystudents][%d] getStudentsForUserOK  %+v", 200, o.Payload)
}

func (o *GetStudentsForUserOK) GetPayload() *models.UsersResponse {
	return o.Payload
}

func (o *GetStudentsForUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UsersResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStudentsForUserNotFound creates a GetStudentsForUserNotFound with default headers values
func NewGetStudentsForUserNotFound() *GetStudentsForUserNotFound {
	return &GetStudentsForUserNotFound{}
}

/*
GetStudentsForUserNotFound describes a response with status code 404, with default header values.

Entity Not Found
*/
type GetStudentsForUserNotFound struct {
	Payload *models.NotFound
}

// IsSuccess returns true when this get students for user not found response has a 2xx status code
func (o *GetStudentsForUserNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get students for user not found response has a 3xx status code
func (o *GetStudentsForUserNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get students for user not found response has a 4xx status code
func (o *GetStudentsForUserNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get students for user not found response has a 5xx status code
func (o *GetStudentsForUserNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get students for user not found response a status code equal to that given
func (o *GetStudentsForUserNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get students for user not found response
func (o *GetStudentsForUserNotFound) Code() int {
	return 404
}

func (o *GetStudentsForUserNotFound) Error() string {
	return fmt.Sprintf("[GET /users/{id}/mystudents][%d] getStudentsForUserNotFound  %+v", 404, o.Payload)
}

func (o *GetStudentsForUserNotFound) String() string {
	return fmt.Sprintf("[GET /users/{id}/mystudents][%d] getStudentsForUserNotFound  %+v", 404, o.Payload)
}

func (o *GetStudentsForUserNotFound) GetPayload() *models.NotFound {
	return o.Payload
}

func (o *GetStudentsForUserNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NotFound)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
