// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Clever/clever-go/models"
)

// GetResourcesForUserReader is a Reader for the GetResourcesForUser structure.
type GetResourcesForUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetResourcesForUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetResourcesForUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetResourcesForUserNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /users/{id}/resources] getResourcesForUser", response, response.Code())
	}
}

// NewGetResourcesForUserOK creates a GetResourcesForUserOK with default headers values
func NewGetResourcesForUserOK() *GetResourcesForUserOK {
	return &GetResourcesForUserOK{}
}

/*
GetResourcesForUserOK describes a response with status code 200, with default header values.

OK Response
*/
type GetResourcesForUserOK struct {
	Payload *models.ResourcesResponse
}

// IsSuccess returns true when this get resources for user o k response has a 2xx status code
func (o *GetResourcesForUserOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get resources for user o k response has a 3xx status code
func (o *GetResourcesForUserOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get resources for user o k response has a 4xx status code
func (o *GetResourcesForUserOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get resources for user o k response has a 5xx status code
func (o *GetResourcesForUserOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get resources for user o k response a status code equal to that given
func (o *GetResourcesForUserOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get resources for user o k response
func (o *GetResourcesForUserOK) Code() int {
	return 200
}

func (o *GetResourcesForUserOK) Error() string {
	return fmt.Sprintf("[GET /users/{id}/resources][%d] getResourcesForUserOK  %+v", 200, o.Payload)
}

func (o *GetResourcesForUserOK) String() string {
	return fmt.Sprintf("[GET /users/{id}/resources][%d] getResourcesForUserOK  %+v", 200, o.Payload)
}

func (o *GetResourcesForUserOK) GetPayload() *models.ResourcesResponse {
	return o.Payload
}

func (o *GetResourcesForUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourcesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetResourcesForUserNotFound creates a GetResourcesForUserNotFound with default headers values
func NewGetResourcesForUserNotFound() *GetResourcesForUserNotFound {
	return &GetResourcesForUserNotFound{}
}

/*
GetResourcesForUserNotFound describes a response with status code 404, with default header values.

Entity Not Found
*/
type GetResourcesForUserNotFound struct {
	Payload *models.NotFound
}

// IsSuccess returns true when this get resources for user not found response has a 2xx status code
func (o *GetResourcesForUserNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get resources for user not found response has a 3xx status code
func (o *GetResourcesForUserNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get resources for user not found response has a 4xx status code
func (o *GetResourcesForUserNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get resources for user not found response has a 5xx status code
func (o *GetResourcesForUserNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get resources for user not found response a status code equal to that given
func (o *GetResourcesForUserNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get resources for user not found response
func (o *GetResourcesForUserNotFound) Code() int {
	return 404
}

func (o *GetResourcesForUserNotFound) Error() string {
	return fmt.Sprintf("[GET /users/{id}/resources][%d] getResourcesForUserNotFound  %+v", 404, o.Payload)
}

func (o *GetResourcesForUserNotFound) String() string {
	return fmt.Sprintf("[GET /users/{id}/resources][%d] getResourcesForUserNotFound  %+v", 404, o.Payload)
}

func (o *GetResourcesForUserNotFound) GetPayload() *models.NotFound {
	return o.Payload
}

func (o *GetResourcesForUserNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NotFound)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
