// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Clever/clever-go/models"
)

// GetSectionsForUserReader is a Reader for the GetSectionsForUser structure.
type GetSectionsForUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSectionsForUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSectionsForUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetSectionsForUserNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSectionsForUserOK creates a GetSectionsForUserOK with default headers values
func NewGetSectionsForUserOK() *GetSectionsForUserOK {
	return &GetSectionsForUserOK{}
}

/*
	GetSectionsForUserOK describes a response with status code 200, with default header values.

OK Response
*/
type GetSectionsForUserOK struct {
	Payload *models.SectionsResponse
}

func (o *GetSectionsForUserOK) Error() string {
	return fmt.Sprintf("[GET /users/{id}/sections][%d] getSectionsForUserOK  %+v", 200, o.Payload)
}
func (o *GetSectionsForUserOK) GetPayload() *models.SectionsResponse {
	return o.Payload
}

func (o *GetSectionsForUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SectionsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSectionsForUserNotFound creates a GetSectionsForUserNotFound with default headers values
func NewGetSectionsForUserNotFound() *GetSectionsForUserNotFound {
	return &GetSectionsForUserNotFound{}
}

/*
	GetSectionsForUserNotFound describes a response with status code 404, with default header values.

Entity Not Found
*/
type GetSectionsForUserNotFound struct {
	Payload *models.NotFound
}

func (o *GetSectionsForUserNotFound) Error() string {
	return fmt.Sprintf("[GET /users/{id}/sections][%d] getSectionsForUserNotFound  %+v", 404, o.Payload)
}
func (o *GetSectionsForUserNotFound) GetPayload() *models.NotFound {
	return o.Payload
}

func (o *GetSectionsForUserNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NotFound)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
