// Code generated by go-swagger; DO NOT EDIT.

package courses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSchoolsForCourseHandlerFunc turns a function with the right signature into a get schools for course handler
type GetSchoolsForCourseHandlerFunc func(GetSchoolsForCourseParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSchoolsForCourseHandlerFunc) Handle(params GetSchoolsForCourseParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetSchoolsForCourseHandler interface for that can handle valid get schools for course params
type GetSchoolsForCourseHandler interface {
	Handle(GetSchoolsForCourseParams, interface{}) middleware.Responder
}

// NewGetSchoolsForCourse creates a new http.Handler for the get schools for course operation
func NewGetSchoolsForCourse(ctx *middleware.Context, handler GetSchoolsForCourseHandler) *GetSchoolsForCourse {
	return &GetSchoolsForCourse{Context: ctx, Handler: handler}
}

/*
	GetSchoolsForCourse swagger:route GET /courses/{id}/schools Courses getSchoolsForCourse

Returns the schools for a course
*/
type GetSchoolsForCourse struct {
	Context *middleware.Context
	Handler GetSchoolsForCourseHandler
}

func (o *GetSchoolsForCourse) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetSchoolsForCourseParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
