// Code generated by go-swagger; DO NOT EDIT.

package courses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSectionsForCourseHandlerFunc turns a function with the right signature into a get sections for course handler
type GetSectionsForCourseHandlerFunc func(GetSectionsForCourseParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSectionsForCourseHandlerFunc) Handle(params GetSectionsForCourseParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetSectionsForCourseHandler interface for that can handle valid get sections for course params
type GetSectionsForCourseHandler interface {
	Handle(GetSectionsForCourseParams, interface{}) middleware.Responder
}

// NewGetSectionsForCourse creates a new http.Handler for the get sections for course operation
func NewGetSectionsForCourse(ctx *middleware.Context, handler GetSectionsForCourseHandler) *GetSectionsForCourse {
	return &GetSectionsForCourse{Context: ctx, Handler: handler}
}

/* GetSectionsForCourse swagger:route GET /courses/{id}/sections Courses getSectionsForCourse

Returns the sections for a course

*/
type GetSectionsForCourse struct {
	Context *middleware.Context
	Handler GetSectionsForCourseHandler
}

func (o *GetSectionsForCourse) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSectionsForCourseParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
