// Code generated by go-swagger; DO NOT EDIT.

package courses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetResourcesForCourseParams creates a new GetResourcesForCourseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetResourcesForCourseParams() *GetResourcesForCourseParams {
	return &GetResourcesForCourseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetResourcesForCourseParamsWithTimeout creates a new GetResourcesForCourseParams object
// with the ability to set a timeout on a request.
func NewGetResourcesForCourseParamsWithTimeout(timeout time.Duration) *GetResourcesForCourseParams {
	return &GetResourcesForCourseParams{
		timeout: timeout,
	}
}

// NewGetResourcesForCourseParamsWithContext creates a new GetResourcesForCourseParams object
// with the ability to set a context for a request.
func NewGetResourcesForCourseParamsWithContext(ctx context.Context) *GetResourcesForCourseParams {
	return &GetResourcesForCourseParams{
		Context: ctx,
	}
}

// NewGetResourcesForCourseParamsWithHTTPClient creates a new GetResourcesForCourseParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetResourcesForCourseParamsWithHTTPClient(client *http.Client) *GetResourcesForCourseParams {
	return &GetResourcesForCourseParams{
		HTTPClient: client,
	}
}

/*
GetResourcesForCourseParams contains all the parameters to send to the API endpoint

	for the get resources for course operation.

	Typically these are written to a http.Request.
*/
type GetResourcesForCourseParams struct {

	// EndingBefore.
	EndingBefore *string

	// ID.
	ID string

	// Limit.
	Limit *int64

	// StartingAfter.
	StartingAfter *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get resources for course params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetResourcesForCourseParams) WithDefaults() *GetResourcesForCourseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get resources for course params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetResourcesForCourseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get resources for course params
func (o *GetResourcesForCourseParams) WithTimeout(timeout time.Duration) *GetResourcesForCourseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get resources for course params
func (o *GetResourcesForCourseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get resources for course params
func (o *GetResourcesForCourseParams) WithContext(ctx context.Context) *GetResourcesForCourseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get resources for course params
func (o *GetResourcesForCourseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get resources for course params
func (o *GetResourcesForCourseParams) WithHTTPClient(client *http.Client) *GetResourcesForCourseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get resources for course params
func (o *GetResourcesForCourseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEndingBefore adds the endingBefore to the get resources for course params
func (o *GetResourcesForCourseParams) WithEndingBefore(endingBefore *string) *GetResourcesForCourseParams {
	o.SetEndingBefore(endingBefore)
	return o
}

// SetEndingBefore adds the endingBefore to the get resources for course params
func (o *GetResourcesForCourseParams) SetEndingBefore(endingBefore *string) {
	o.EndingBefore = endingBefore
}

// WithID adds the id to the get resources for course params
func (o *GetResourcesForCourseParams) WithID(id string) *GetResourcesForCourseParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get resources for course params
func (o *GetResourcesForCourseParams) SetID(id string) {
	o.ID = id
}

// WithLimit adds the limit to the get resources for course params
func (o *GetResourcesForCourseParams) WithLimit(limit *int64) *GetResourcesForCourseParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get resources for course params
func (o *GetResourcesForCourseParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithStartingAfter adds the startingAfter to the get resources for course params
func (o *GetResourcesForCourseParams) WithStartingAfter(startingAfter *string) *GetResourcesForCourseParams {
	o.SetStartingAfter(startingAfter)
	return o
}

// SetStartingAfter adds the startingAfter to the get resources for course params
func (o *GetResourcesForCourseParams) SetStartingAfter(startingAfter *string) {
	o.StartingAfter = startingAfter
}

// WriteToRequest writes these params to a swagger request
func (o *GetResourcesForCourseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.EndingBefore != nil {

		// query param ending_before
		var qrEndingBefore string

		if o.EndingBefore != nil {
			qrEndingBefore = *o.EndingBefore
		}
		qEndingBefore := qrEndingBefore
		if qEndingBefore != "" {

			if err := r.SetQueryParam("ending_before", qEndingBefore); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.StartingAfter != nil {

		// query param starting_after
		var qrStartingAfter string

		if o.StartingAfter != nil {
			qrStartingAfter = *o.StartingAfter
		}
		qStartingAfter := qrStartingAfter
		if qStartingAfter != "" {

			if err := r.SetQueryParam("starting_after", qStartingAfter); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
