// Code generated by go-swagger; DO NOT EDIT.

package schools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Clever/clever-go/models"
)

// GetSectionsForSchoolReader is a Reader for the GetSectionsForSchool structure.
type GetSectionsForSchoolReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSectionsForSchoolReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSectionsForSchoolOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetSectionsForSchoolNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSectionsForSchoolOK creates a GetSectionsForSchoolOK with default headers values
func NewGetSectionsForSchoolOK() *GetSectionsForSchoolOK {
	return &GetSectionsForSchoolOK{}
}

/*
	GetSectionsForSchoolOK describes a response with status code 200, with default header values.

OK Response
*/
type GetSectionsForSchoolOK struct {
	Payload *models.SectionsResponse
}

func (o *GetSectionsForSchoolOK) Error() string {
	return fmt.Sprintf("[GET /schools/{id}/sections][%d] getSectionsForSchoolOK  %+v", 200, o.Payload)
}
func (o *GetSectionsForSchoolOK) GetPayload() *models.SectionsResponse {
	return o.Payload
}

func (o *GetSectionsForSchoolOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SectionsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSectionsForSchoolNotFound creates a GetSectionsForSchoolNotFound with default headers values
func NewGetSectionsForSchoolNotFound() *GetSectionsForSchoolNotFound {
	return &GetSectionsForSchoolNotFound{}
}

/*
	GetSectionsForSchoolNotFound describes a response with status code 404, with default header values.

Entity Not Found
*/
type GetSectionsForSchoolNotFound struct {
	Payload *models.NotFound
}

func (o *GetSectionsForSchoolNotFound) Error() string {
	return fmt.Sprintf("[GET /schools/{id}/sections][%d] getSectionsForSchoolNotFound  %+v", 404, o.Payload)
}
func (o *GetSectionsForSchoolNotFound) GetPayload() *models.NotFound {
	return o.Payload
}

func (o *GetSectionsForSchoolNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NotFound)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
