// Code generated by go-swagger; DO NOT EDIT.

package schools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Clever/clever-go/models"
)

// GetUsersForSchoolReader is a Reader for the GetUsersForSchool structure.
type GetUsersForSchoolReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUsersForSchoolReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUsersForSchoolOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetUsersForSchoolNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /schools/{id}/users] getUsersForSchool", response, response.Code())
	}
}

// NewGetUsersForSchoolOK creates a GetUsersForSchoolOK with default headers values
func NewGetUsersForSchoolOK() *GetUsersForSchoolOK {
	return &GetUsersForSchoolOK{}
}

/*
GetUsersForSchoolOK describes a response with status code 200, with default header values.

OK Response
*/
type GetUsersForSchoolOK struct {
	Payload *models.UsersResponse
}

// IsSuccess returns true when this get users for school o k response has a 2xx status code
func (o *GetUsersForSchoolOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get users for school o k response has a 3xx status code
func (o *GetUsersForSchoolOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get users for school o k response has a 4xx status code
func (o *GetUsersForSchoolOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get users for school o k response has a 5xx status code
func (o *GetUsersForSchoolOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get users for school o k response a status code equal to that given
func (o *GetUsersForSchoolOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get users for school o k response
func (o *GetUsersForSchoolOK) Code() int {
	return 200
}

func (o *GetUsersForSchoolOK) Error() string {
	return fmt.Sprintf("[GET /schools/{id}/users][%d] getUsersForSchoolOK  %+v", 200, o.Payload)
}

func (o *GetUsersForSchoolOK) String() string {
	return fmt.Sprintf("[GET /schools/{id}/users][%d] getUsersForSchoolOK  %+v", 200, o.Payload)
}

func (o *GetUsersForSchoolOK) GetPayload() *models.UsersResponse {
	return o.Payload
}

func (o *GetUsersForSchoolOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UsersResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsersForSchoolNotFound creates a GetUsersForSchoolNotFound with default headers values
func NewGetUsersForSchoolNotFound() *GetUsersForSchoolNotFound {
	return &GetUsersForSchoolNotFound{}
}

/*
GetUsersForSchoolNotFound describes a response with status code 404, with default header values.

Entity Not Found
*/
type GetUsersForSchoolNotFound struct {
	Payload *models.NotFound
}

// IsSuccess returns true when this get users for school not found response has a 2xx status code
func (o *GetUsersForSchoolNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get users for school not found response has a 3xx status code
func (o *GetUsersForSchoolNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get users for school not found response has a 4xx status code
func (o *GetUsersForSchoolNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get users for school not found response has a 5xx status code
func (o *GetUsersForSchoolNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get users for school not found response a status code equal to that given
func (o *GetUsersForSchoolNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get users for school not found response
func (o *GetUsersForSchoolNotFound) Code() int {
	return 404
}

func (o *GetUsersForSchoolNotFound) Error() string {
	return fmt.Sprintf("[GET /schools/{id}/users][%d] getUsersForSchoolNotFound  %+v", 404, o.Payload)
}

func (o *GetUsersForSchoolNotFound) String() string {
	return fmt.Sprintf("[GET /schools/{id}/users][%d] getUsersForSchoolNotFound  %+v", 404, o.Payload)
}

func (o *GetUsersForSchoolNotFound) GetPayload() *models.NotFound {
	return o.Payload
}

func (o *GetUsersForSchoolNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NotFound)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
