// Code generated by go-swagger; DO NOT EDIT.

package schools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Clever/clever-go/models"
)

// GetSchoolsReader is a Reader for the GetSchools structure.
type GetSchoolsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSchoolsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSchoolsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /schools] getSchools", response, response.Code())
	}
}

// NewGetSchoolsOK creates a GetSchoolsOK with default headers values
func NewGetSchoolsOK() *GetSchoolsOK {
	return &GetSchoolsOK{}
}

/*
GetSchoolsOK describes a response with status code 200, with default header values.

OK Response
*/
type GetSchoolsOK struct {
	Payload *models.SchoolsResponse
}

// IsSuccess returns true when this get schools o k response has a 2xx status code
func (o *GetSchoolsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get schools o k response has a 3xx status code
func (o *GetSchoolsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get schools o k response has a 4xx status code
func (o *GetSchoolsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get schools o k response has a 5xx status code
func (o *GetSchoolsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get schools o k response a status code equal to that given
func (o *GetSchoolsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get schools o k response
func (o *GetSchoolsOK) Code() int {
	return 200
}

func (o *GetSchoolsOK) Error() string {
	return fmt.Sprintf("[GET /schools][%d] getSchoolsOK  %+v", 200, o.Payload)
}

func (o *GetSchoolsOK) String() string {
	return fmt.Sprintf("[GET /schools][%d] getSchoolsOK  %+v", 200, o.Payload)
}

func (o *GetSchoolsOK) GetPayload() *models.SchoolsResponse {
	return o.Payload
}

func (o *GetSchoolsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SchoolsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
