// Code generated by go-swagger; DO NOT EDIT.

package schools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDistrictForSchoolParams creates a new GetDistrictForSchoolParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDistrictForSchoolParams() *GetDistrictForSchoolParams {
	return &GetDistrictForSchoolParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDistrictForSchoolParamsWithTimeout creates a new GetDistrictForSchoolParams object
// with the ability to set a timeout on a request.
func NewGetDistrictForSchoolParamsWithTimeout(timeout time.Duration) *GetDistrictForSchoolParams {
	return &GetDistrictForSchoolParams{
		timeout: timeout,
	}
}

// NewGetDistrictForSchoolParamsWithContext creates a new GetDistrictForSchoolParams object
// with the ability to set a context for a request.
func NewGetDistrictForSchoolParamsWithContext(ctx context.Context) *GetDistrictForSchoolParams {
	return &GetDistrictForSchoolParams{
		Context: ctx,
	}
}

// NewGetDistrictForSchoolParamsWithHTTPClient creates a new GetDistrictForSchoolParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDistrictForSchoolParamsWithHTTPClient(client *http.Client) *GetDistrictForSchoolParams {
	return &GetDistrictForSchoolParams{
		HTTPClient: client,
	}
}

/*
GetDistrictForSchoolParams contains all the parameters to send to the API endpoint

	for the get district for school operation.

	Typically these are written to a http.Request.
*/
type GetDistrictForSchoolParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get district for school params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDistrictForSchoolParams) WithDefaults() *GetDistrictForSchoolParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get district for school params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDistrictForSchoolParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get district for school params
func (o *GetDistrictForSchoolParams) WithTimeout(timeout time.Duration) *GetDistrictForSchoolParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get district for school params
func (o *GetDistrictForSchoolParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get district for school params
func (o *GetDistrictForSchoolParams) WithContext(ctx context.Context) *GetDistrictForSchoolParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get district for school params
func (o *GetDistrictForSchoolParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get district for school params
func (o *GetDistrictForSchoolParams) WithHTTPClient(client *http.Client) *GetDistrictForSchoolParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get district for school params
func (o *GetDistrictForSchoolParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get district for school params
func (o *GetDistrictForSchoolParams) WithID(id string) *GetDistrictForSchoolParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get district for school params
func (o *GetDistrictForSchoolParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetDistrictForSchoolParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
