// Code generated by go-swagger; DO NOT EDIT.

package terms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetTermsParams creates a new GetTermsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTermsParams() *GetTermsParams {
	return &GetTermsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTermsParamsWithTimeout creates a new GetTermsParams object
// with the ability to set a timeout on a request.
func NewGetTermsParamsWithTimeout(timeout time.Duration) *GetTermsParams {
	return &GetTermsParams{
		timeout: timeout,
	}
}

// NewGetTermsParamsWithContext creates a new GetTermsParams object
// with the ability to set a context for a request.
func NewGetTermsParamsWithContext(ctx context.Context) *GetTermsParams {
	return &GetTermsParams{
		Context: ctx,
	}
}

// NewGetTermsParamsWithHTTPClient creates a new GetTermsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTermsParamsWithHTTPClient(client *http.Client) *GetTermsParams {
	return &GetTermsParams{
		HTTPClient: client,
	}
}

/*
GetTermsParams contains all the parameters to send to the API endpoint

	for the get terms operation.

	Typically these are written to a http.Request.
*/
type GetTermsParams struct {

	// Count.
	Count *string

	// EndingBefore.
	EndingBefore *string

	// Limit.
	Limit *int64

	// StartingAfter.
	StartingAfter *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get terms params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTermsParams) WithDefaults() *GetTermsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get terms params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTermsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get terms params
func (o *GetTermsParams) WithTimeout(timeout time.Duration) *GetTermsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get terms params
func (o *GetTermsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get terms params
func (o *GetTermsParams) WithContext(ctx context.Context) *GetTermsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get terms params
func (o *GetTermsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get terms params
func (o *GetTermsParams) WithHTTPClient(client *http.Client) *GetTermsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get terms params
func (o *GetTermsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCount adds the count to the get terms params
func (o *GetTermsParams) WithCount(count *string) *GetTermsParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the get terms params
func (o *GetTermsParams) SetCount(count *string) {
	o.Count = count
}

// WithEndingBefore adds the endingBefore to the get terms params
func (o *GetTermsParams) WithEndingBefore(endingBefore *string) *GetTermsParams {
	o.SetEndingBefore(endingBefore)
	return o
}

// SetEndingBefore adds the endingBefore to the get terms params
func (o *GetTermsParams) SetEndingBefore(endingBefore *string) {
	o.EndingBefore = endingBefore
}

// WithLimit adds the limit to the get terms params
func (o *GetTermsParams) WithLimit(limit *int64) *GetTermsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get terms params
func (o *GetTermsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithStartingAfter adds the startingAfter to the get terms params
func (o *GetTermsParams) WithStartingAfter(startingAfter *string) *GetTermsParams {
	o.SetStartingAfter(startingAfter)
	return o
}

// SetStartingAfter adds the startingAfter to the get terms params
func (o *GetTermsParams) SetStartingAfter(startingAfter *string) {
	o.StartingAfter = startingAfter
}

// WriteToRequest writes these params to a swagger request
func (o *GetTermsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Count != nil {

		// query param count
		var qrCount string

		if o.Count != nil {
			qrCount = *o.Count
		}
		qCount := qrCount
		if qCount != "" {

			if err := r.SetQueryParam("count", qCount); err != nil {
				return err
			}
		}
	}

	if o.EndingBefore != nil {

		// query param ending_before
		var qrEndingBefore string

		if o.EndingBefore != nil {
			qrEndingBefore = *o.EndingBefore
		}
		qEndingBefore := qrEndingBefore
		if qEndingBefore != "" {

			if err := r.SetQueryParam("ending_before", qEndingBefore); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.StartingAfter != nil {

		// query param starting_after
		var qrStartingAfter string

		if o.StartingAfter != nil {
			qrStartingAfter = *o.StartingAfter
		}
		qStartingAfter := qrStartingAfter
		if qStartingAfter != "" {

			if err := r.SetQueryParam("starting_after", qStartingAfter); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
