// Code generated by go-swagger; DO NOT EDIT.

package terms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Clever/clever-go/models"
)

// GetDistrictForTermReader is a Reader for the GetDistrictForTerm structure.
type GetDistrictForTermReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDistrictForTermReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDistrictForTermOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetDistrictForTermNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /terms/{id}/district] getDistrictForTerm", response, response.Code())
	}
}

// NewGetDistrictForTermOK creates a GetDistrictForTermOK with default headers values
func NewGetDistrictForTermOK() *GetDistrictForTermOK {
	return &GetDistrictForTermOK{}
}

/*
GetDistrictForTermOK describes a response with status code 200, with default header values.

OK Response
*/
type GetDistrictForTermOK struct {
	Payload *models.DistrictResponse
}

// IsSuccess returns true when this get district for term o k response has a 2xx status code
func (o *GetDistrictForTermOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get district for term o k response has a 3xx status code
func (o *GetDistrictForTermOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get district for term o k response has a 4xx status code
func (o *GetDistrictForTermOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get district for term o k response has a 5xx status code
func (o *GetDistrictForTermOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get district for term o k response a status code equal to that given
func (o *GetDistrictForTermOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get district for term o k response
func (o *GetDistrictForTermOK) Code() int {
	return 200
}

func (o *GetDistrictForTermOK) Error() string {
	return fmt.Sprintf("[GET /terms/{id}/district][%d] getDistrictForTermOK  %+v", 200, o.Payload)
}

func (o *GetDistrictForTermOK) String() string {
	return fmt.Sprintf("[GET /terms/{id}/district][%d] getDistrictForTermOK  %+v", 200, o.Payload)
}

func (o *GetDistrictForTermOK) GetPayload() *models.DistrictResponse {
	return o.Payload
}

func (o *GetDistrictForTermOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DistrictResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDistrictForTermNotFound creates a GetDistrictForTermNotFound with default headers values
func NewGetDistrictForTermNotFound() *GetDistrictForTermNotFound {
	return &GetDistrictForTermNotFound{}
}

/*
GetDistrictForTermNotFound describes a response with status code 404, with default header values.

Entity Not Found
*/
type GetDistrictForTermNotFound struct {
	Payload *models.NotFound
}

// IsSuccess returns true when this get district for term not found response has a 2xx status code
func (o *GetDistrictForTermNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get district for term not found response has a 3xx status code
func (o *GetDistrictForTermNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get district for term not found response has a 4xx status code
func (o *GetDistrictForTermNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get district for term not found response has a 5xx status code
func (o *GetDistrictForTermNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get district for term not found response a status code equal to that given
func (o *GetDistrictForTermNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get district for term not found response
func (o *GetDistrictForTermNotFound) Code() int {
	return 404
}

func (o *GetDistrictForTermNotFound) Error() string {
	return fmt.Sprintf("[GET /terms/{id}/district][%d] getDistrictForTermNotFound  %+v", 404, o.Payload)
}

func (o *GetDistrictForTermNotFound) String() string {
	return fmt.Sprintf("[GET /terms/{id}/district][%d] getDistrictForTermNotFound  %+v", 404, o.Payload)
}

func (o *GetDistrictForTermNotFound) GetPayload() *models.NotFound {
	return o.Payload
}

func (o *GetDistrictForTermNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NotFound)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
