// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Name name
//
// swagger:model Name
type Name struct {

	// first
	First *string `json:"first,omitempty"`

	// last
	Last *string `json:"last,omitempty"`

	// middle
	Middle *string `json:"middle,omitempty"`
}

// Validate validates this name
func (m *Name) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this name based on context it is used
func (m *Name) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Name) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Name) UnmarshalBinary(b []byte) error {
	var res Name
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
