// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Term term
//
// swagger:model Term
type Term struct {

	// district
	District string `json:"district,omitempty"`

	// end date
	// Format: datetime
	EndDate *strfmt.DateTime `json:"end_date,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name *string `json:"name,omitempty"`

	// start date
	// Format: datetime
	StartDate *strfmt.DateTime `json:"start_date,omitempty"`
}

// Validate validates this term
func (m *Term) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEndDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStartDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Term) validateEndDate(formats strfmt.Registry) error {
	if swag.IsZero(m.EndDate) { // not required
		return nil
	}

	if err := validate.FormatOf("end_date", "body", "datetime", m.EndDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Term) validateStartDate(formats strfmt.Registry) error {
	if swag.IsZero(m.StartDate) { // not required
		return nil
	}

	if err := validate.FormatOf("start_date", "body", "datetime", m.StartDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this term based on context it is used
func (m *Term) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Term) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Term) UnmarshalBinary(b []byte) error {
	var res Term
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
